version: '3.7'

services:  
  queue:
    image: rabbitmq:3
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'pswd'
    ports:
      - "5672:5672"
  
  consumer:
    build: ./Consumer
    restart: always
    links:
      - queue
#    timeout: 30s
    healthcheck:
      # test: ["CMD"]
#      test: ["CMD_SHELL", "curl -f amqp://user:pswd@queue:5672"]
      interval: 30s
      timeout: 10s
      # retries: 5
  
  producer:
    build: ./Producer
    restart: always
    links:
      - queue
#    timeout: 30s
    healthcheck:
      # test: ["CMD"]
#      test: ["CMD_SHELL", "curl -f amqp://user:pswd@queue:5672"]
      interval: 30s
      timeout: 10s

