version: '2'

services:  
  queue:
    image: rabbitmq:3
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'pswd'
#    hostname: queue
    ports:
      - "5672:5672"
  
  consumer:
    build: ./Consumer
    restart: always
    links:
      - queue
#    timeout: 30s
  
  producer:
    build: ./Producer
    restart: always
    links:
      - queue
#    timeout: 30s

# promprog_default 

# networks:
#   default:
#     external:
#       name: localhost
